version: "3.8"

services:
  proxy:
    image: nginx:1.21.6-alpine # ~5mb
    container_name: napenshe-server
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: unless-stopped