version: "3.8"

services:
  proxy:
    image: nginx:1.21.6-alpine # ~5mb
    container_name: napenshe-server
    networks:
      - devops
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - web

networks: 
  devops:
    external: true
    name: devops_net